### ISSUE TITLE
Can't run the demo, fineUploaderDnd function undefined

### ISSUE THREAD

**Issue by ShoresOfNowhere** [FineUploader/video-frame-uploader#2] opened 2016-12-10 11:23 UTC
I'm going mad, but I can't make the included index.html demo page to work.

I've checked all the script includes, and they all load fine, and in firebug's net panel no load errors are shown, but the js console shows this error: 

TypeError: $(...).fineUploaderDnd is not a function on line 279 of client.js

I don't find this function anywhere in fineuploader docs, nor it seems to be present in any script that index.html includes...

Maybe (for sure, I might say) I'm missing something so stupid that I'll bash my head on the wall, but what is it?

Please help me! ;)

**Comment by rnicholus** [comment] 2016-12-10 15:08
Looks like you uncovered a regression in the Fine Uploader build. This likely happened during the major build system refactor in version 5.11.0. I filed a bug in the underlying project at FineUploader/fine-uploader#1700. I'll fix this ASAP (probably this weekend) and push out the fix as v5.11.10, along with another smaller user-contributed build fix.

**Comment by ShoresOfNowhere** [comment] 2016-12-10 15:54
Oh, so I really encountered a bug? Wow, this is nice, I was blaming myself... :)

Thanks, and looking forward to the upcoming milestone!

**Comment by rnicholus** [comment] 2016-12-11 03:51
Fixed in 5.11.10 of Fine Uploader (which I just published).

If you `npm install` again, you'll pull down 5.11.10 and all should be well. Thanks for the report!

**Closed as completed by rnicholus** 2016-12-11 03:51 UTC
Labels: bug
